yarnPath: .yarn/releases/yarn-3.0.2.cjs
nodeLinker: node-modules
npmScopes:
  "signature":
    npmRegistryServer: "https://pkgs.dev.azure.com/Signature-OpenSource/Feeds/_packaging/NetCore3/npm/registry/"
